export const GET_MAIN_INFO = 'GET_MAIN_INFO';
export const CHANGE_LOCALE = 'CHANGE_LOCALE';
export const SET_UI_TRANSLATIONS_LOADING = 'SET_UI_TRANSLATIONS_LOADING';
export const SET_UI_TRANSLATIONS_LOADED = 'SET_UI_TRANSLATIONS_LOADED';

